apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      name: http
  selector:
    app: flask-app